"""
ProjectCatalog — Authoritative Curated Engineering Project Catalog.

=============================================================================
METHODOLOGICAL NOTE:
=============================================================================
This catalog represents CURATED PRODUCT KNOWLEDGE. It is NOT claimed to be
statistically learned from the ML model or generated by an LLM.

All skill references strictly adhere to the locked 29-feature canonical vocabulary:
ai, autocad, cad, cloud, communication, critical_thinking, data_analysis,
database_design, database_systems, design, design_optimization, excel,
experimentation, lab_work, machine_learning, matlab, negotiation,
observation, plc, power_analysis, programming, pscad, python, recording,
research, sales, simulation, team_management, web_development.
=============================================================================
"""

from __future__ import annotations

from typing import Dict, List, Optional, Set
from app.schemas.project_recommendation import ProjectItem


CURATED_PROJECTS: List[ProjectItem] = [
    # -----------------------------------------------------------------------
    # Track 1: Software Development & Engineering
    # -----------------------------------------------------------------------
    ProjectItem(
        project_id="sde-proj-01",
        title="High-Throughput E-Commerce REST API & Order Service",
        career_track="Software Development & Engineering",
        description=(
            "Architect a resilient multi-tier REST API for order processing with ACID "
            "transaction boundaries, relational database indexing, and structured error handling."
        ),
        difficulty="Intermediate",
        estimated_effort="25 hours",
        skills_demonstrated=["programming", "python", "database_systems", "database_design", "web_development"],
        skills_targeted=["database_systems", "database_design", "web_development"],
        prerequisites=["programming", "python"],
        recommended_stage=2,
        portfolio_value="high",
        suggested_deliverables=[
            "OpenAPI / Swagger documentation with request validation schemas",
            "Relational PostgreSQL migration scripts with foreign keys and index definitions",
            "Modular service repository with comprehensive pytest suite",
        ],
        suggested_evidence=[
            "Public GitHub repository with automated CI workflow",
            "Technical README with architectural diagram and entity-relationship model",
            "Integration test suite achieving >80% statement coverage",
            "Live deployment URL or container execution recording",
        ],
        technology_stack=["Python", "FastAPI", "PostgreSQL", "SQLAlchemy", "Docker"],
    ),
    ProjectItem(
        project_id="sde-proj-02",
        title="Full-Stack Collaborative Issue & Sprint Tracker",
        career_track="Software Development & Engineering",
        description=(
            "Develop an end-to-end agile issue tracking web application featuring relational "
            "schema modeling, asynchronous state management, and role-based permissions."
        ),
        difficulty="Intermediate",
        estimated_effort="30 hours",
        skills_demonstrated=["programming", "web_development", "database_design", "team_management", "design"],
        skills_targeted=["web_development", "design", "team_management"],
        prerequisites=["programming", "database_systems"],
        recommended_stage=3,
        portfolio_value="high",
        suggested_deliverables=[
            "Interactive single-page application interface with responsive design",
            "Normalized relational database schema with audit log triggers",
            "Team collaboration sprint board with role authorization",
        ],
        suggested_evidence=[
            "Source code repository with commit history following conventional commits",
            "UI walkthrough recording showcasing backlog grooming and status transitions",
            "Security and authentication design document",
        ],
        technology_stack=["TypeScript", "React", "Node.js / Python", "PostgreSQL", "TailwindCSS"],
    ),
    ProjectItem(
        project_id="sde-proj-03",
        title="Distributed Task Queue & Performance Profiling Harness",
        career_track="Software Development & Engineering",
        description=(
            "Build an asynchronous worker engine with dead-letter queueing, concurrency "
            "controls, runtime latency profiling, and memory bottleneck analysis."
        ),
        difficulty="Advanced",
        estimated_effort="35 hours",
        skills_demonstrated=["programming", "python", "critical_thinking", "design_optimization", "simulation"],
        skills_targeted=["design_optimization", "simulation", "critical_thinking"],
        prerequisites=["programming", "python", "database_systems"],
        recommended_stage=4,
        portfolio_value="very_high",
        suggested_deliverables=[
            "Asynchronous task queue engine with exponential backoff retry policies",
            "Benchmark profiling harness comparing latency and throughput under load",
            "Memory and execution flamegraph analysis report",
        ],
        suggested_evidence=[
            "Source repository with reproducible benchmarking scripts",
            "Performance optimization report with before/after p99 latency metrics",
            "Chaos load simulation script demonstrating worker failover recovery",
        ],
        technology_stack=["Python", "Redis", "Asyncio", "Py-Spy / cProfile", "Docker Compose"],
    ),
    ProjectItem(
        project_id="sde-proj-04",
        title="Cloud-Native Microservices Gateway & Service Registry",
        career_track="Software Development & Engineering",
        description=(
            "Construct an edge reverse proxy and service registry providing dynamic route "
            "dispatch, token-bucket rate limiting, and structured observability telemetry."
        ),
        difficulty="Advanced",
        estimated_effort="35 hours",
        skills_demonstrated=["programming", "web_development", "cloud", "design", "critical_thinking"],
        skills_targeted=["cloud", "design", "critical_thinking"],
        prerequisites=["programming", "web_development"],
        recommended_stage=4,
        portfolio_value="very_high",
        suggested_deliverables=[
            "API gateway routing layer with token-bucket rate limiting",
            "Health-check heartbeat monitor and dynamic service registration",
            "Centralized OpenTelemetry tracing configuration",
        ],
        suggested_evidence=[
            "Architecture blueprint diagram depicting ingress traffic flow",
            "End-to-end integration test harness simulating downstream service failures",
            "Cloud deployment manifest (Docker / Kubernetes or Serverless)",
        ],
        technology_stack=["Python / Go", "Docker", "Traefik / Nginx", "OpenTelemetry", "AWS / GCP"],
    ),

    # -----------------------------------------------------------------------
    # Track 2: AI & Machine Learning Engineering
    # -----------------------------------------------------------------------
    ProjectItem(
        project_id="aiml-proj-01",
        title="End-to-End Supervised ML Pipeline & Evaluation Suite",
        career_track="AI & Machine Learning Engineering",
        description=(
            "Build a production-grade machine learning training and evaluation pipeline with "
            "exploratory data analysis, cross-validation, and metric baselining."
        ),
        difficulty="Intermediate",
        estimated_effort="25 hours",
        skills_demonstrated=["programming", "python", "data_analysis", "machine_learning"],
        skills_targeted=["data_analysis", "machine_learning"],
        prerequisites=["programming", "python"],
        recommended_stage=2,
        portfolio_value="high",
        suggested_deliverables=[
            "Jupyter exploratory notebook detailing distribution plots and missing value handling",
            "Modular Python package for feature transformers and model estimators",
            "Comparative performance report across precision, recall, and ROC-AUC curves",
        ],
        suggested_evidence=[
            "GitHub repository with unit tests for data transformation pipelines",
            "Model card documenting dataset demographics, limitations, and baseline metrics",
            "Serialized model artifact with deterministic verification script",
        ],
        technology_stack=["Python", "NumPy", "Pandas", "Scikit-Learn", "Matplotlib / Seaborn"],
    ),
    ProjectItem(
        project_id="aiml-proj-02",
        title="Deep Neural Network Architecture & Representation Learning",
        career_track="AI & Machine Learning Engineering",
        description=(
            "Design, train, and evaluate a deep neural network architecture for complex "
            "unstructured representation learning with regularization and learning rate schedules."
        ),
        difficulty="Intermediate",
        estimated_effort="30 hours",
        skills_demonstrated=["python", "machine_learning", "ai", "critical_thinking"],
        skills_targeted=["ai", "critical_thinking"],
        prerequisites=["python", "data_analysis", "machine_learning"],
        recommended_stage=3,
        portfolio_value="high",
        suggested_deliverables=[
            "Custom neural network architecture implementation using PyTorch or TensorFlow",
            "Training diagnostic telemetry logging loss curves and gradient norms",
            "Ablation study comparing architecture variants and regularization techniques",
        ],
        suggested_evidence=[
            "Public repository with reproducible training scripts and random seed controls",
            "Experiment tracking logs (TensorBoard or Weights & Biases export)",
            "Inference demo script verifying model predictions on holdout samples",
        ],
        technology_stack=["Python", "PyTorch / TensorFlow", "Torchvision / HuggingFace", "TensorBoard"],
    ),
    ProjectItem(
        project_id="aiml-proj-03",
        title="Cloud ML Inference Microservice with Low-Latency Model Serving",
        career_track="AI & Machine Learning Engineering",
        description=(
            "Package a trained ML artifact into a high-throughput REST inference microservice "
            "with schema validation, batch prediction, and containerization."
        ),
        difficulty="Advanced",
        estimated_effort="30 hours",
        skills_demonstrated=["programming", "python", "machine_learning", "cloud", "database_systems"],
        skills_targeted=["cloud", "database_systems"],
        prerequisites=["python", "machine_learning", "programming"],
        recommended_stage=3,
        portfolio_value="very_high",
        suggested_deliverables=[
            "FastAPI model serving application with Pydantic request validation",
            "Docker container with multi-stage build optimizing runtime size",
            "Automated load testing script measuring p95 and p99 inference latency",
        ],
        suggested_evidence=[
            "Container registry artifact or Dockerfile with automated build verification",
            "API documentation and Postman / curl demonstration collection",
            "Cloud deployment log or live staging endpoint",
        ],
        technology_stack=["Python", "FastAPI", "Docker", "ONNX Runtime / Triton", "AWS / Render"],
    ),
    ProjectItem(
        project_id="aiml-proj-04",
        title="Controlled A/B Model Experimentation & Latency Optimization",
        career_track="AI & Machine Learning Engineering",
        description=(
            "Implement an offline-to-online statistical experimentation framework with "
            "post-training quantization, hyperparameter tuning, and drift monitoring."
        ),
        difficulty="Advanced",
        estimated_effort="35 hours",
        skills_demonstrated=["python", "machine_learning", "experimentation", "design_optimization", "research", "simulation"],
        skills_targeted=["experimentation", "design_optimization", "research", "simulation"],
        prerequisites=["python", "machine_learning", "data_analysis"],
        recommended_stage=4,
        portfolio_value="very_high",
        suggested_deliverables=[
            "Bayesian hyperparameter optimization and model quantization pipeline",
            "A/B testing simulation module evaluating statistical power and minimum detectable effect",
            "Data distribution drift detection script using Kolmogorov-Smirnov / PSI metrics",
        ],
        suggested_evidence=[
            "Formal research-style technical report summarizing methodology and findings",
            "Benchmarking chart showing model compression vs accuracy retention",
            "Interactive evaluation notebook with statistical hypothesis tests",
        ],
        technology_stack=["Python", "Optuna", "SciPy", "Evidently / Alibi-Detect", "PyTorch Quantization"],
    ),

    # -----------------------------------------------------------------------
    # Track 3: Data Analytics & Business Intelligence
    # -----------------------------------------------------------------------
    ProjectItem(
        project_id="dabi-proj-01",
        title="Executive Business Performance & Revenue Analytics Dashboard",
        career_track="Data Analytics & Business Intelligence",
        description=(
            "Construct an executive financial and sales KPI dashboard using advanced spreadsheet "
            "modeling, cohort retention curves, and dynamic scenario modeling."
        ),
        difficulty="Beginner",
        estimated_effort="18 hours",
        skills_demonstrated=["excel", "data_analysis", "critical_thinking"],
        skills_targeted=["excel", "data_analysis"],
        prerequisites=[],
        recommended_stage=1,
        portfolio_value="medium",
        suggested_deliverables=[
            "Interactive Excel / Spreadsheet workbook with dynamic INDEX/MATCH lookups and pivot models",
            "Cohort retention matrix and customer acquisition cost (CAC) sensitivity table",
            "Executive one-page KPI summary dashboard",
        ],
        suggested_evidence=[
            "Workbook file with clean formula documentation and data dictionary",
            "Executive slide deck summarizing primary business risks and revenue drivers",
            "Video walkthrough explaining key dashboard levers and scenario sensitivities",
        ],
        technology_stack=["Excel / Google Sheets", "Power Query", "Pivot Tables", "Financial Modeling"],
    ),
    ProjectItem(
        project_id="dabi-proj-02",
        title="Enterprise Relational Data Warehouse & SQL Analytics Engine",
        career_track="Data Analytics & Business Intelligence",
        description=(
            "Design a dimensional star schema data mart and execute complex analytical SQL "
            "queries with window functions, recursive CTEs, and customer segmentation."
        ),
        difficulty="Intermediate",
        estimated_effort="25 hours",
        skills_demonstrated=["database_systems", "database_design", "data_analysis"],
        skills_targeted=["database_systems", "database_design"],
        prerequisites=["excel"],
        recommended_stage=2,
        portfolio_value="high",
        suggested_deliverables=[
            "Star schema entity-relationship diagram with fact and dimension tables",
            "SQL analytics query suite calculating rolling averages, churn, and RFM tiers",
            "Data transformation pipeline normalizing raw operational records",
        ],
        suggested_evidence=[
            "SQL repository with modular migration scripts and schema constraints",
            "Query performance optimization log documenting index impact on query plans",
            "Data validation checklist ensuring referential integrity and zero orphan rows",
        ],
        technology_stack=["PostgreSQL / DuckDB", "SQL DDL/DML", "DBDiagram", "dbt Core"],
    ),
    ProjectItem(
        project_id="dabi-proj-03",
        title="Automated Customer Churn Analytics & Predictive Forecasting",
        career_track="Data Analytics & Business Intelligence",
        description=(
            "Automate an end-to-end data pipeline in Python to identify churn drivers, forecast "
            "quarterly trends, and present strategic recommendations to stakeholders."
        ),
        difficulty="Intermediate",
        estimated_effort="28 hours",
        skills_demonstrated=["python", "data_analysis", "machine_learning", "communication"],
        skills_targeted=["python", "machine_learning", "communication"],
        prerequisites=["data_analysis", "database_systems"],
        recommended_stage=3,
        portfolio_value="high",
        suggested_deliverables=[
            "Automated ETL transformation script in Python cleaning raw CRM exports",
            "Predictive churn scoring model with feature importance rankings",
            "Stakeholder-facing slide deck translating statistical findings into actionable retention tactics",
        ],
        suggested_evidence=[
            "Clean GitHub repository with Python analysis scripts and reproducible environment",
            "Executive memo summarizing projected ROI of suggested retention campaign",
            "Dashboard visualization mockups (Tableau / PowerBI or Seaborn)",
        ],
        technology_stack=["Python", "Pandas", "Scikit-Learn", "PowerBI / Tableau", "Plotly"],
    ),
    ProjectItem(
        project_id="dabi-proj-04",
        title="Market Competitive Intelligence & Strategic Negotiation Brief",
        career_track="Data Analytics & Business Intelligence",
        description=(
            "Synthesize macroeconomic market trends, quantitative competitor benchmarks, and "
            "cross-functional requirements into an executive strategic decision memo."
        ),
        difficulty="Advanced",
        estimated_effort="30 hours",
        skills_demonstrated=["communication", "research", "critical_thinking", "negotiation", "team_management"],
        skills_targeted=["research", "negotiation", "team_management", "critical_thinking"],
        prerequisites=["communication", "data_analysis"],
        recommended_stage=4,
        portfolio_value="very_high",
        suggested_deliverables=[
            "Comprehensive competitive benchmark matrix covering industry KPIs and pricing",
            "Decision memo with tradeoff matrix and multi-stakeholder compromise framework",
            "Executive presentation deck structured for senior leadership sign-off",
        ],
        suggested_evidence=[
            "Market research report with complete citations and methodology documentation",
            "Presentation recording delivering the business recommendation within 10 minutes",
            "Risk assessment table highlighting sensitivity to key assumptions",
        ],
        technology_stack=["Market Research Frameworks", "Financial Modeling", "Executive Storytelling", "Minto Pyramid Principle"],
    ),

    # -----------------------------------------------------------------------
    # Track 4: Cloud, DevOps & Systems Engineering
    # -----------------------------------------------------------------------
    ProjectItem(
        project_id="cdev-proj-01",
        title="Automated Infrastructure Scripting & Linux CLI Tooling",
        career_track="Cloud, DevOps & Systems Engineering",
        description=(
            "Build a robust command-line automation utility in Python for systems administration, "
            "log rotation, resource monitoring, and automated backups."
        ),
        difficulty="Beginner",
        estimated_effort="20 hours",
        skills_demonstrated=["programming", "python", "critical_thinking"],
        skills_targeted=["programming", "python"],
        prerequisites=[],
        recommended_stage=1,
        portfolio_value="medium",
        suggested_deliverables=[
            "CLI utility with POSIX argument parsing and descriptive exit codes",
            "Automated log parsing and health alerting script with email/webhook integration",
            "Cron-compatible backup runner with rotation and integrity hashing",
        ],
        suggested_evidence=[
            "GitHub repository with modular Python CLI packaging (pyproject.toml)",
            "Automated test suite mocking OS system calls and filesystem operations",
            "Terminal cast recording illustrating CLI operations and error handling",
        ],
        technology_stack=["Python", "Bash", "Click / Typer", "Linux POSIX APIs", "GitHub Actions"],
    ),
    ProjectItem(
        project_id="cdev-proj-02",
        title="Containerized Microservice Infrastructure & Database Clustering",
        career_track="Cloud, DevOps & Systems Engineering",
        description=(
            "Containerize multi-tier web applications with reproducible networking, database "
            "connection pooling, volume persistence, and health-check orchestration."
        ),
        difficulty="Intermediate",
        estimated_effort="25 hours",
        skills_demonstrated=["programming", "cloud", "database_systems", "database_design"],
        skills_targeted=["cloud", "database_systems", "database_design"],
        prerequisites=["programming", "python"],
        recommended_stage=2,
        portfolio_value="high",
        suggested_deliverables=[
            "Optimized multi-stage Dockerfiles enforcing non-root user permissions",
            "Docker Compose orchestration manifest linking web, worker, and database tiers",
            "Automated database migration and replica failover configuration",
        ],
        suggested_evidence=[
            "Source code repository with container linting and vulnerability scanning (Trivy)",
            "Architecture topology diagram outlining network segments and volume mounts",
            "Disaster recovery runbook with verified step-by-step restoration procedures",
        ],
        technology_stack=["Docker", "Docker Compose", "PostgreSQL Replicas", "Redis", "Trivy"],
    ),
    ProjectItem(
        project_id="cdev-proj-03",
        title="Cloud CI/CD Pipeline & Zero-Downtime Deployment Automation",
        career_track="Cloud, DevOps & Systems Engineering",
        description=(
            "Architect a fully automated CI/CD pipeline featuring automated testing, semantic "
            "versioning, container publishing, and zero-downtime blue/green deployment."
        ),
        difficulty="Intermediate",
        estimated_effort="30 hours",
        skills_demonstrated=["cloud", "web_development", "team_management", "critical_thinking"],
        skills_targeted=["web_development", "team_management", "critical_thinking"],
        prerequisites=["programming", "cloud"],
        recommended_stage=3,
        portfolio_value="high",
        suggested_deliverables=[
            "GitHub Actions workflow pipeline with parallel test runners and artifact caching",
            "Zero-downtime deployment script with automated rollback upon health check failure",
            "Branch protection strategy and team pull-request review policy documentation",
        ],
        suggested_evidence=[
            "Public repository with green CI/CD badge and real deployment history",
            "Deployment log demonstrating automatic rollback on simulated error injection",
            "Team operational guide detailing release gates and changelog automation",
        ],
        technology_stack=["GitHub Actions", "Docker Registry", "Nginx / Traefik", "AWS / DigitalOcean", "Semantic Release"],
    ),
    ProjectItem(
        project_id="cdev-proj-04",
        title="Chaos Engineering Simulation & Site Reliability Observability",
        career_track="Cloud, DevOps & Systems Engineering",
        description=(
            "Deploy an observability stack (metrics, logs, traces) and execute controlled "
            "chaos experiments simulating network latency, pod failures, and disk exhaustion."
        ),
        difficulty="Advanced",
        estimated_effort="35 hours",
        skills_demonstrated=["cloud", "simulation", "design_optimization", "critical_thinking", "team_management"],
        skills_targeted=["simulation", "design_optimization", "critical_thinking", "team_management"],
        prerequisites=["programming", "cloud"],
        recommended_stage=4,
        portfolio_value="very_high",
        suggested_deliverables=[
            "Observability stack deployment with Prometheus metrics and Grafana alerting dashboards",
            "Chaos experiment scenario definitions testing system fault resilience",
            "Incident post-mortem report following a simulated production outage",
        ],
        suggested_evidence=[
            "Grafana dashboard export displaying SLI/SLO latency and error budget trends",
            "Automated chaos test suite demonstrating automated service healing",
            "Blameless post-mortem document analyzing incident root cause and preventative action items",
        ],
        technology_stack=["Prometheus", "Grafana", "Chaos Toolkit / LitmusChaos", "Kubernetes / Docker", "OpenTelemetry"],
    ),
]


class ProjectCatalogService:
    """Singleton service providing access to the authoritative curated project catalog."""

    _instance: Optional[ProjectCatalogService] = None

    @classmethod
    def get_instance(cls) -> ProjectCatalogService:
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    def get_all_projects(self) -> List[ProjectItem]:
        """Returns all curated projects in the catalog."""
        return list(CURATED_PROJECTS)

    def get_projects_for_track(self, career_track: str) -> List[ProjectItem]:
        """Returns projects curated for a specific career track."""
        return [p for p in CURATED_PROJECTS if p.career_track == career_track]

    def get_project_by_id(self, project_id: str) -> Optional[ProjectItem]:
        """Returns a specific project by its unique ID."""
        for p in CURATED_PROJECTS:
            if p.project_id == project_id:
                return p
        return None

    def validate_canonical_skills(self, canonical_vocab: Set[str]) -> bool:
        """
        Validates that EVERY skill in every project belongs to the canonical vocabulary.
        Raises ValueError if violations are detected.
        """
        violations: List[str] = []
        for project in CURATED_PROJECTS:
            for s in project.skills_demonstrated:
                if s not in canonical_vocab:
                    violations.append(f"Project '{project.project_id}' demonstrated skill '{s}' not canonical")
            for s in project.skills_targeted:
                if s not in canonical_vocab:
                    violations.append(f"Project '{project.project_id}' targeted skill '{s}' not canonical")
            for s in project.prerequisites:
                if s not in canonical_vocab:
                    violations.append(f"Project '{project.project_id}' prerequisite skill '{s}' not canonical")

        if violations:
            raise ValueError(f"Project catalog validation failed:\n" + "\n".join(violations))
        return True
